name: vscode-markdown-languageserver
summary: Markdown Language Server
description: |
  Server capabilities
    * Completions for Markdown links.
    * Folding of Markdown regions, block elements, and header sections.
    * Smart selection for inline elements, block elements, and header sections.
    * Document Symbols for quick navigation to headers in a document.
    * Workspace Symbols for quick navigation to headers in the workspace
    * Document links for making Markdown links in a document clickable.
    * Find all references to headers and links across all Markdown files in the workspace.
    * Rename of headers and links across all Markdown files in the workspace.
    * Go to definition from links to headers or link definitions.
    * (experimental) Pull diagnostics (validation) for links.

adopt-info: vscode-markdown-languageserver
grade: stable
confinement: strict
base: core20

layout:
  /usr/local/share/.config/yarn:
    bind: $SNAP/usr/local/share/.config/yarn

apps:
  vscode-markdown-languageserver:
    command: bin/node $SNAP/usr/local/share/.config/yarn/global/node_modules/vscode-markdown-languageserver/out/node/main.js
    plugs:
      - network
      - home

parts:
  vscode-markdown-languageserver:
    plugin: npm
    source: https://github.com/microsoft/vscode.git
    build-environment:
      - NODEJS_FIXED_VERSION: "v16.20.1"
    npm-node-version: $NODEJS_FIXED_VERSION
    # add packages so we can npm install on vscode itself as it's node
    # dependecies are needed to compile the json-languageserver
    build-packages:
      - pkg-config
      - python
      - libx11-dev
      - libxkbfile-dev
      - libsecret-1-dev
      - jq
      - moreutils
    override-build: |
      # install the official nodejs so we get the expected npm version
      if [ $SNAP_ARCH == "amd64" ]; then
        ARCH=x64
      elif [ $SNAP_ARCH == "armhf" ]; then
        ARCH=armv7l
      elif [ $SNAP_ARCH == "ppc64el" ]; then
        ARCH=ppc64le
      else
        ARCH=$SNAP_ARCH
      fi
      curl -s https://nodejs.org/dist/"${NODEJS_FIXED_VERSION}"/node-"${NODEJS_FIXED_VERSION}"-linux-$ARCH.tar.gz | tar xzf - -C "$SNAPCRAFT_PART_INSTALL" --strip-components=1
      npm install -g yarn
      npm install -g gulp
      yarn install
      cd extensions/markdown-language-features/server
      yarn install
      yarn run compile
      yarn global add --prefix $SNAPCRAFT_PART_INSTALL $(yarn pack . | grep "Wrote tarball to" | cut -f2 -d'"')
      # fixup install location
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/local/share/.config
      mv /usr/local/share/.config/yarn $SNAPCRAFT_PART_INSTALL/usr/local/share/.config
      snapcraftctl set-version $(jq -r .version package.json)
